import { sql } from 'drizzle-orm';
import { check, timestamp, uuid, type AnyPgColumn } from 'drizzle-orm/pg-core';

/** uuid PK, generated by Postgres (gen_random_uuid is core since PG13). */
export function id() {
  return uuid().primaryKey().defaultRandom();
}

/**
 * created_at/updated_at on every table (ARCHITECTURE §3). updated_at is
 * maintained app-level via $onUpdate rather than a DB trigger: repositories
 * are the only write path (lint-enforced), and a plpgsql trigger per table
 * would be forward-only-migration ceremony. Writes that bypass Drizzle
 * (psql, future raw SQL) will NOT bump updated_at.
 */
export function timestamps() {
  return {
    createdAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp({ withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  };
}

/**
 * CHECK constraint pinning an enum-like text column to its @careerforge/core
 * value set — DB-level integrity without native pg enums (whose ALTER TYPE
 * semantics fight forward-only migrations, ADR-0003).
 */
export function enumCheck(name: string, column: AnyPgColumn, values: readonly string[]) {
  const list = sql.raw(values.map((value) => `'${value}'`).join(', '));
  return check(name, sql`${column} in (${list})`);
}
